version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: api-nestjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: db-nestjs-app
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=cursonestjs

  dbtest:
    build: .docker/postgres
    container_name: db-test-app
    restart: always
    tty: true
    ports:
      - "5433:5432"
    volumes:
      - .docker/dbdatatest:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dbtest

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-nestjs-app
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db